name:                monadf
version:             0.1.0.0
github:              "github.com/emiflake/monadf"
license:             BSD3
author:              "emiflake"
maintainer:          "example@example.com"
copyright:           "2018 emiflake"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/monadf#readme>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.*
- text == 1.2.3.0
- mtl == 2.2.2

library:
  source-dirs: src

executables:
  mdbf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadf

tests:
  monadf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadf
